# Generated by Django 4.0.5 on 2022-06-30 02:29

from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(
        first_name="Heder", 
        last_name="Milani", 
        email="heder.milani@email.com",
        phone="01234567890",
        address="Addrees heder 01",
        description="Primeiro usuário cadastrado").save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
        
    ]
